### ISSUE TITLE
Stake balance shown improvement

### ISSUE THREAD

**Issue by mattia480** [polispay/polis#122]
It would be useful to add the real amount of staking balance.
In the current versions the balance that could participate in stake is shown, it would be useful to show also the amount of coin that participate in stake considering that only single UTXO with a minimum amount of 100 Polis participate in stake.

### Expected behaviour
Additionally show the stake balance considering that only single UTXO with a minimum amount of 100 Polis participate in stake

### Actual behaviour
In the current version is only shown the amount of coin that could partecipate in stake

### What version of Polis Core are you using?
Polis Core version v1.6.2.0-0798cfe89 (64-bit)

**Comment by eabz** [comment]
Thanks for the report @mattia480.
Since we are on the latests stages of the launch of the Polis new network and since this issue is only visual and focused on UI we don't have time to fix this bug.
