### ISSUE TITLE
pwalletMain was not declared in this scope

### ISSUE THREAD

**Issue by cipig** [polispay/polis#45]
Can't compile the wallet, the following error is shown:
```
rpc/misc.cpp: In function ‘UniValue getstakingstatus(const JSONRPCRequest&)’:
rpc/misc.cpp:1155:9: error: ‘pwalletMain’ was not declared in this scope
     if (pwalletMain) {
         ^~~~~~~~~~~
```
I used this configure options:
./configure --with-incompatible-bdb --with-gui=no --disable-tests --disable-bench --without-miniupnpc --disable-zmq --disable-wallet

**Comment by cipig** [comment]
Sure, i used master branch `git clone https://github.com/polispay/polis` and i use debian 9. I suspect it is because of the option "--disable-wallet". I run electrum-servers for POLIS, and don't need wallet support.

**Comment by eabz** [comment]
Currently master and develop branches are broken. You should use tag v1.3.1 or tag 1.3.1-patched.

**Comment by eabz** [comment]
Also, you can use electrumx, polis is already integrated there.

**Comment by cipig** [comment]
Thanks a lot, using branch 1.3.1-patched-release worked. And yes, i use electrumx and run couple of electrumx-servers for BarterDEX. POLIS can be traded there, btw :-)

**Comment by eabz** [comment]
Nice. Didn't know about Polis on BarterDex, let's announce it. 
Also we are working on electrum wallets so, if you are able to share electrum servers url will be nice.

**Comment by cipig** [comment]
Sure, the electrumx-server are configured here: https://github.com/jl777/coins/blob/master/electrums/POLIS
electrum1-3.cipig.net, port 10075. The IPs will differ, depending on where the client is located (we have 3 locations: Europe, North America and Korea)
