### ISSUE TITLE
[Platform Specific] Win32 Versions not Syncing

### ISSUE THREAD

**Issue by PrettyBoyHelios** [polispay/polis#56]
### Describe the issue
Since v1.4.3 Wallets running over Windows in its 32-bits version fail to sync the blockchain and reindexing gets them stuck at block 209720 (a.k.a. PoS Fork).

#### If so, please list the steps to reproduce below:
1. Wallet stops syncing 
2. Reindex
3. Wallet gets stuck at 209,720

### Expected behaviour
Wallet should sync to the newest block.

### Actual behaviour
Wallet gets stuck at 209720.

### What version of Polis Core are you using?
v1.4.3 - v1.4.5

### Machine specs:
- OS: Windows 7 (More?)
- CPU: 32-bit

**Comment by PrettyBoyHelios** [comment]
This issue is duplicated, all 32 bit platforms seem to be having this issue

**Comment by eabz** [comment]
I think the issue is solved on 3cadcda016a0d0c79d7ff1e1a4b92da4753bf113
We need to test, compiling from source.

**Comment by eabz** [comment]
Reverted 3cadcda016a0d0c79d7ff1e1a4b92da4753bf113
Confirmed full solution on: 167c0094ff881759af84d045030ba4656871f716

**Comment by eabz** [comment]
Reopen until we fully test it.

**Comment by eabz** [comment]
All sync issues should be solved right now.
