### ISSUE TITLE
[Platform Specific] Arm Versions not Syncing

### ISSUE THREAD

**Issue by space-q** [polispay/polis#58]
### Describe the issue

Wallets running over RaspberryPi (Raspbian 9.4) fail to sync the blockchain and reindexing gets them stuck at block 209720 (a.k.a. PoS Fork).

#### If so, please list the steps to reproduce below:
1. Wallet stops syncing
2. Reindex
3. Wallet gets stuck at block 209720

### Expected behaviour
Wallet should sync to the newest block.

### Actual behaviour
Wallet gets stuck at block 209720

### What version of Polis Core are you using?
1.4.6 (poliscore-1.4.6-arm-linux-gnueabihf.tar.gz)
1.4.7 (poliscore-1.4.7-arm-linux-gnueabihf.tar.gz)

### Machine specs:
- OS: Raspbian 9.4

### Any extra information that might be useful in the debugging process.
Downloading bootstrap doesn't help (I tried various sources) as wallet reports corrupted block database and require reindex

**Comment by btcgripe** [comment]
same problem raspi wallet stuck 209720

**Comment by eabz** [comment]
I think this issue is solved on 3cadcda016a0d0c79d7ff1e1a4b92da4753bf113 
Can someone compile from source and test?

**Comment by luis9614** [comment]
Sure

**Comment by PrettyBoyHelios** [comment]
Sure

**Comment by PrettyBoyHelios** [comment]
What platform did the user test at?

**Comment by PrettyBoyHelios** [comment]
The patch works for initial sync, but a reindex causes the wallet to get stuck again at block 209720.

**Comment by eabz** [comment]
@PrettyBoyHelios Can we try again, reverted last patch and new solution works pretty fast on reindex.

**Comment by PrettyBoyHelios** [comment]
Sure, let me compile for Windows & Linux. Have you tested in 64 bits as well?

**Comment by eabz** [comment]
No sorry, haven't tested it. I'll reopen the issue until we fully test it. 
Only tested on Mac OS.
