### ISSUE TITLE
[Wallet] Recover Transactions

### ISSUE THREAD

**Issue by PrettyBoyHelios** [polispay/polis#68]
### Describe the issue
Several users reported a constant need to recover transactions at least, with some even having to perform a reindex just so that the wallet could display their funds correctly.

### Expected behaviour

Wallet should display the total user's funds.

### Actual behaviour
Wallet shows partial amounts of the user's funds, even when checking that info from console.

### What version of Polis Core are you using?
1.4.x

**Comment by tperalta82** [comment]
./poliscore-1.4.10/bin/polis-cli -datadir=".data" getbalance ""
10000.25719813
./poliscore-1.4.10/bin/polis-cli -datadir=".data" stop
./poliscore-1.4.10/bin/polisd -datadir=".data" -rescan -zapwallettxes=1
Polis Core server starting
./poliscore-1.4.10/bin/polis-cli -datadir=".data" getbalance 
11309.85719813


Still happening
