### ISSUE TITLE
Can't run polis cli

### ISSUE THREAD

**Issue by strogiyotec** [polispay/polis#70]
I download the latest tag of POLIS (1.4.7) when I run polisd (Ubuntu 16.04) I got the following error

./polisd: 1: ./polisd: ELF��u: not found
./polisd: 2: ./polisd: Syntax error: word unexpected (expecting ")")

How to fix it?

**Comment by eabz** [comment]
@strogiyotec Can you confirm you are still having the issue?
Sometimes the issue is on the program you use to monitor the node. A reboot may fix it.

**Comment by Lollipopster** [comment]
@eabz You close this ticket , thank you for helping

**Comment by strogiyotec** [comment]
@eabz You can close this ticket , thank you for helping
