### ISSUE TITLE
Polis cli doesn't show masternodes

### ISSUE THREAD

**Issue by Lollipopster** [polispay/polis#71]
I want to get number of masternodes
```
./polis-cli masternode count
```
This is the output
```
{
  "total": 0,
  "ps_compatible": 0,
  "enabled": 0,
  "qualify": 0
}
```

**Comment by WieliczkaPL** [comment]
try this

 polis-cli masternode count
{
  "total": 3641,
  "ps_compatible": 2999,
  "enabled": 2999,
  "qualify": 2638
}

**Comment by strogiyotec** [comment]
> try this
> 
> ` polis-cli masternode count`
> 
> ```
> {
>   "total": 3641,
>   "ps_compatible": 2999,
>   "enabled": 2999,
>   "qualify": 2638
> }
> ```

I don't know what was the problem , but when I reinstalled cli it started to work

**Comment by eabz** [comment]
@Lollipopster 
When you start the node, you need to let your node to update messages from other nodes, the command to see the status of the synchronisation is `mnsync`. Until is ready you will se wrong data. 
We are looking to solve this using our own versions of the Dash DIPS for a deterministic masternode list, but it will take some time.

**Comment by Lollipopster** [comment]
@eabz  the problem appeared again , I have rebooted my polisd and was waiting about 2 hours but nothing was changed
```
./polis-cli mnsync status
{
  "AssetID": 0,
  "AssetName": "MASTERNODE_SYNC_INITIAL",
  "AssetStartTime": 1547459596,
  "Attempt": 0,
  "IsBlockchainSynced": false,
  "IsMasternodeListSynced": false,
  "IsWinnersListSynced": false,
  "IsSynced": false,
  "IsFailed": false
}
```
And this is info output
```
./polis-cli getinfo
{
  "version": 1040700,
  "protocolversion": 70211,
  "walletversion": 61000,
  "balance": 0.00000000,
  "blocks": 213797,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 2.341578121621944,
  "testnet": false,
  "keypoololdest": 1540839475,
  "keypoolsize": 999,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}
```
What should I do ?

**Comment by eabz** [comment]
@Lollipopster You can force the node to resync using `mnsync reset`
Also to do a clean resync you can delete mnpayments.dat and mncache.dat and governance.dat and restart the wallet.

**Comment by WieliczkaPL** [comment]
@Lollipopster 
Hi  fastest way is downloading new blocks from 1-229000 and waiting for sync of newer ones 

script and blocks below ( type without stoping polis)



` wget -q https://raw.githubusercontent.com/cryptosharks131/Polis/master/bootstrap.sh`

` bash bootstrap.sh`

and all works fine, try it
