### ISSUE TITLE
Zorin 12.4

### ISSUE THREAD

**Issue by d4n1e77** [polispay/polis#85]
This issue tracker is only for technical issues related to Polis Core.

### Describe the issue
Have the onlinen Version https://zorinos.com/help/install-zorin-os/
when i open the polis-qt i have the following issue, so i cant type anything in the Wallet.

Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT venvironmenal variable to provide an additional search parth, add`':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/

This porblem only have the Polis wallet. The SINS, SMART works fine.

#### If so, please list the steps to reproduce below:
1. Start over the Terminal the ./polis-qt
2. the XKB issue comes polis wallet starts and work
3. when i want to write something in the debug console or want to unlock the Wallet i cant type anything in the text line

### Expected behaviour
Tell us what should happen

### What version of Polis Core are you using?
Clitent version v1.4.10.0-fe22c6fb7

Thanks for your help!

**Comment by eabz** [comment]
Using v1.4.11 should fix the issue.
