### ISSUE TITLE
Problems installing poliscore-1.4.10-osx-unsigned.dmg

### ISSUE THREAD

**Issue by macronnie** [polispay/polis#86]
Hi,
 I can not install poliscore-1.4.10-osx-unsigned.dmg on the latest macOS Sierra !

When you click on the disk image , nothing happens... 

I have the latest Command Line tools xcode10.1 installed.

![Skärmavbild 2019-03-26 kl  22 54 03](https://user-images.githubusercontent.com/48967738/55036564-4f858400-501b-11e9-9baf-326fe6787c2f.png)
![Skärmavbild 2019-03-26 kl  22 21 29](https://user-images.githubusercontent.com/48967738/55036575-590eec00-501b-11e9-9030-d6a8fc2cf3ad.png)

New release someone?

Reg. Ronnie

**Comment by eabz** [comment]
Yes, here is the new version: 
https://github.com/polispay/polis/releases/download/v1.4.11/poliscore-1.4.11-osx-unsigned.dmg
