### ISSUE TITLE
Wallet  v1.4.13 does not synchronize

### ISSUE THREAD

**Issue by AndAntAnd** [polispay/polis#89]
After upgrade core to  v1.4.13 wallet does not synchronize. polis.conf upgraded in accordance with recommendations. Sync halts on May 5th 18.32

Just tried to install 1.4.14. The same - halts on may 5th - no active connections with Polis network.

Pls help!

**Comment by dickbaua** [comment]
I have the same Problem.

**Comment by crackfoo** [comment]
same

**Comment by crackfoo** [comment]
same with v1.4.14

**Comment by eabz** [comment]
@AndAntAnd @crackfoo @dickbaua v1.4.15 should fix this issue. Please watch https://github.com/polispay/polis/releases/tag/v1.4.15
